<!DOCTYPE html>
<html>
<head>
    <title>HOTEL</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
        }

        h1 {
            color: #333;
        }

        hr {
            border: 1px solid #333;
            margin: 20px auto;
        }

        h3 {
            color: #555;
            margin-top: 20px;
        }

        h4 {
            color: red;
            margin-top: 10px;
        }
    </style>
</head>
<body>
<h1>HOTEL</h1>
<hr>
<h3>Забронировать номер</h3>
<h4>Время занято, выберите другое время</h4>
</body>
</html>
